[build]
  command = "npm run build"
  publish = "dist/compraventa-coches/browser"

[[redirects]]
  from = "http://tallercarslistanco.es/*"
  to = "https://tallercarslistanco.es/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.tallercarslistanco.es/*"
  to = "https://tallercarslistanco.es/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.tallercarslistanco.es/*"
  to = "https://tallercarslistanco.es/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://autolistanco.es/*"
  to = "https://tallercarslistanco.es/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://autolistanco.es/*"
  to = "https://tallercarslistanco.es/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.autolistanco.es/*"
  to = "https://tallercarslistanco.es/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.autolistanco.es/*"
  to = "https://tallercarslistanco.es/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
